### ISSUE TITLE
Feature request: `flixgen` missing the most important category

### ISSUE THREAD

**Issue by haakonstorm** [alfredapp/streaming-genres-workflow#1]
Netflix category 1964512 "Cyberpunk" - contains all the goodies Netflix has to offer!
e.g. https://www.netflix.com/browse/genre/1964512
:)

**Comment by vitorgalvao** [comment]
Thank you. Added in [2022.3](https://github.com/alfredapp/streaming-genres-workflow/releases/tag/2022.3).
